vatancomputer/store/urls.py
from django.urls import path
from . import views
from django.http import JsonResponse

app_name = "store"

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('view/<int:productId>', views.view, name='view'),
    path('update_item/', views.update_item, name='update_item'),
    path('complete_order/', views.complete_order, name='complete_order')
]

vatancomputer/vatancomputer/urls.py
from django.contrib import admin
from django.urls import path, include

# for upload image to database
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vatancomputer/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.firstName} {self.lastName}"

class ProductDetail(models.Model):
    description = models.CharField(max_length=500)
    
    # Teknik Özellikler
    batteryType = models.CharField(max_length=50)
    batteryCellCount = models.CharField(max_length=50)
    security = models.CharField(max_length=50)
    
    # Ram Özellikleri
    ram = models.CharField(max_length=50)
    ramType = models.CharField(max_length=50)
    
    # Ekran Kartı
    graphicsCardChipsetBrand = models.CharField(max_length=50)
    graphicsCardChipset = models.CharField(max_length=50)
    graphicsCardMemoryType = models.CharField(max_length=50)
    graphicsCardMemory = models.CharField(max_length=50)
    graphicsCardType = models.CharField(max_length=50)
    
    # HDD Özellikleri
    diskCapacity = models.CharField(max_length=50)
    diskType = models.CharField(max_length=50)
    
    # Power
    power = models.CharField(max_length=50)
    
    # Multimedia
    multimediaHeadphoneOutput = models.CharField(max_length=50)
    multimediaFeatures = models.CharField(max_length=50)
    multimediaCamera = models.CharField(max_length=50)
    multimediaFingerprintReader = models.CharField(max_length=50)
    
    # Keyboard
    keyboard = models.CharField(max_length=50)
    
    # Monitor
    monitor = models.CharField(max_length=50)
    
    # İşletim Sistemi
    operatingSystem = models.CharField(max_length=50)
    
    # Genel Özellikler
    color = models.CharField(max_length=50)
    fastCharging = models.CharField(max_length=50)
    origin = models.CharField(max_length=50)
    guarantee = models.CharField(max_length=50)
    
    # İşlemci Tipi
    processorType = models.CharField(max_length=50)
    processorGen = models.CharField(max_length=50)
    processorTech = models.CharField(max_length=50)
    processorNum = models.CharField(max_length=50)
    processorSpeed = models.CharField(max_length=50)
    processorCache = models.CharField(max_length=50)
    processorCore = models.CharField(max_length=50)
    
    # Ekran Özellikleri
    screenSize = models.CharField(max_length=50)
    screenrRefreshRate = models.CharField(max_length=50)
    screenFeatures = models.CharField(max_length=50)
    screenResolution = models.CharField(max_length=50)
    screenIPS = models.CharField(max_length=50)
    screenFullHD = models.CharField(max_length=50)
    screenHD = models.CharField(max_length=50)
    screenTN = models.CharField(max_length=50)
    screenTouch = models.CharField(max_length=50)
    
    # Bağlantı Özellikleri + Portlar
    connectionSpecificationUSB20 = models.CharField(max_length=50)
    connectionSpecificationUSB32 = models.CharField(max_length=50)
    connectionSpecificationUSBTypeC = models.CharField(max_length=50)
    connectionSpecificationBluetoothTech = models.CharField(max_length=50)
    connectionSpecificationEtherner = models.CharField(max_length=50)
    connectionSpecificationWiFi = models.CharField(max_length=50)
    connectionSpecificationHDMI = models.CharField(max_length=50)
    connectionSpecificationCardSlot = models.CharField(max_length=50)
    connectionSpecificationBluetooth = models.CharField(max_length=50)
    
    # Diğer
    illuminatedKeyboard = models.CharField(max_length=50)
    intendedUse1 = models.CharField(max_length=50)
    intendedUse2 = models.CharField(max_length=50)
    manufacturerPartNumber = models.CharField(max_length=50)
    
    # Ağırlık & boyutlar
    weight = models.CharField(max_length=50)
    height = models.CharField(max_length=50)
    width = models.CharField(max_length=50)
    
    def __str__(self):
        return str(f"{self.product_set.get(productDetail=self).brand} - {self.product_set.get(productDetail=self).name}")
    
       
class Product(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    summary = models.CharField(max_length=100)
    amount = models.IntegerField()
    price = models.FloatField()
    productDetail = models.ForeignKey(ProductDetail, on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return f"{self.brand} {self.name}"
    
    @property
    def getImage(self):
        try:
            image_url = self.itemimage_set.filter(product=self, image_order=1).get().image.url
        except:
            image_url = ''
        return image_url
    
    @property
    def getImageList(self):
        try:
            image_urls = self.itemimage_set.filter(product=self).order_by('image_order').all()
        except:
            image_urls = []
        return image_urls

class ItemImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    image_order = models.IntegerField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def summary_item_count(self):
        orderitems = self.orderitem_set.all()
        item_count = 0
        for orderitem in orderitems:
            item_count += orderitem.amount
        return item_count
    
    @property
    def summary_item_price(self):
        orderitems = self.orderitem_set.all()
        price_sum = 0
        for orderitem in orderitems:
            price_sum += orderitem.amount * orderitem.product.price
        return price_sum
    


# Order ile OrderItem mantığına internetten baktım
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def summary_price(self):
        return (self.amount * self.product.price)

class PaymentInformation(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    card_name = models.CharField(max_length=50, null=False, blank=False)
    card_number = models.CharField(max_length=19, null=False, blank=False)
    expires_end = models.CharField(max_length=5, null=False, blank=False)
    cvv = models.CharField(max_length=3, null=False, blank=False)

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    payment_info  = models.ForeignKey(PaymentInformation, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=500)
    address_optional = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=20)
    zipcode = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.id)

vatancomputer/store/views.py
from django.shortcuts import render
from . import models
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
import json

# Create your views here.

def store(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = models.Order.objects.get_or_create(customer=customer, complete=False)
    else:
        order = { 'summary_item_count':0, 'summary_item_price':0 }
    products = models.Product.objects.all()
    context = { "products" : products, "order":order }
    return render(request, 'store/store.html', context=context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        # https://www.letscodemore.com/blog/django-get-or-create/
        order, created = models.Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        print("çalışıyor")
        
    else:
        items = []
        order = { 'summary_item_count':0, 'summary_item_price':0 }
        
    context = { "order" : order, "items" : items }
    return render(request, 'store/cart.html', context=context)

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = models.Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = { 'summary_item_count':0, 'summary_item_price':0 }
    
    if (request.method == "POST") and (request.POST is not None):
        clean_data = request.POST
        print("add 1")
        if (request.user.is_authenticated == False):
            firstName = clean_data['firstName']
            lastName = clean_data['lastName']
            username = clean_data['username']
            email = clean_data['email']
        else:
            print("add 2")
            address1 = clean_data['address']
            address2 = clean_data['address2']
            city = clean_data['city']
            zipcode = clean_data['zipcode']
            payment_method = clean_data['paymentMethod']
            cartName = clean_data['cartName']
            cartNumber = clean_data['cartNumber']
            cartExpiration = clean_data['cartExpiration']
            cartCvv = clean_data['cartCvv']

            paymentInformation = models.PaymentInformation(customer=customer, payment_method=payment_method, card_name=cartName
                                                                        ,card_number=cartNumber, expires_end=cartExpiration, cvv=cartCvv)
            paymentInformation.save()
            shippingAdress = models.ShippingAddress.objects.create(customer=customer, payment_info=paymentInformation, 
                                                order=order, address=address1, address_optional=address2, 
                                                city=city, zipcode=zipcode)
            shippingAdress.save()
            return redirect(reverse('store:store'))

            
    product = models.Product.objects.all()
    context = { "order" : order, "items" : items }
    return render(request, 'store/checkout.html', context=context)

def view(request, productId):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = models.Order.objects.get_or_create(customer=customer, complete=False)
    else:
        order = { 'summary_item_count':0, 'summary_item_price':0 }
        
    
    product = models.Product.objects.get(id=productId)
    productImages = list(product.getImageList)
    activeImage = None
    for product in productImages:
        if product.image_order == 1:
            activeImage = product
            productImages.remove(product)
    iterator = range(2, len(productImages))
    product = models.Product.objects.get(id=productId)
    context = { "order" : order, "product" : product, "productImages" : productImages, "activeImage" : activeImage, "iterator" : range(1, len(productImages) + 1) }
    return render(request, 'store/view.html', context=context)

def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    
    customer = request.user.customer
    product = models.Product.objects.get(id=productId)
    order, created = models.Order.objects.get_or_create(customer=customer, complete='False')
    orderItem, created = models.OrderItem.objects.get_or_create(order=order, product=product)
    
    if action == "add":
        orderItem.amount = orderItem.amount + 1
    elif action == "remove":
        orderItem.amount = orderItem.amount - 1
        
    orderItem.save()
    
    if orderItem.amount <= 0:
        orderItem.delete()
    
    return JsonResponse('Item was updated!', safe=False)

def complete_order(request):
    data = json.loads(request.body)
    orderId = data['orderId']
    action = data['action']
    
    customer = request.user.customer
    order, created = models.Order.objects.get_or_create(customer=customer, complete='False')
    orderItems = order.orderitem_set.all()
    
    if action == "complete" and len(orderItems) > 0:
        for item in orderItems:
            item.product.amount = item.product.amount - item.amount
            item.product.save()
        order.complete = True
    
    order.save()
        
    return JsonResponse('Payment is successful!', safe=False)

vatancomputer/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<!-- Container -->
<div class="container-md" id="cart-container">
    <div class="items thumbnail">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="item-image" scope="col"></th>
                    <th scope="col">Ürün Adı</th>
                    <th scope="col">Fiyat</th>
                    <th scope="col">Miktar</th>
                    <th scope="col">Toplam Fiyat</th>
                </tr>
            </thead>

            <tbody>
                {% if items.count == 0 %}
                <tr>
                    <td id="item-image"> </td>
                    <td id="item-image" colspan="4">Ürün yok</td>
                </tr>
                {% endif %}
                {% for item in items %}
                <tr>
                    <td id="item-image">
                        <img src="{{ item.product.getImage }}" alt="item_image">
                    </td>
                    <td>
                        {{ item.product.name }}
                        <br>
                        <small class="item-brand">{{ item.product.brand }}</small>
                    </td>
                    <td>{{ item.product.price|floatformat:2 }} TL</td>
                    <td>
                        {{ item.amount }}
                        <div class="quantity">
                            <img data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">

                            <img data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}">
                        </div>
                    </td>
                    <td>{{ item.summary_price|floatformat:2 }} TL</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="items-info thumbnail">
        <a href="{% url 'store:store' %}" class="btn btn-outline-dark no-curved">← Alışverişe Geri Dön</a>
        <br>
        <br>
        <div class="shopping-info">
            <h4>
                Ürün Adeti: <strong>{{ order.summary_item_count }}</strong>
            </h4>
            <h4>
                Ürün Fiyatı: <strong>{{ order.summary_item_price|floatformat:2 }} TL</strong>
            </h4>
            <hr>
            <a class="btn btn-success no-curved" style="float:right; margin:5px; clear:both;"
                href="{% url 'store:checkout' %}">Sipariş
                Toplamı</a>
        </div>
    </div>
</div>
{% endblock %}

vatancomputer/store/templates/store/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vatan Bilgisayar</title>

    <!-- Bootstrap Css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- External Css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
     <!--Inline JavaScript  -->
    <script text="text/javascript">
        var user = '{{request.user}}';

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>

<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'store:store' %}">Vatan Bilgisayar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
                aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample04">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'store:store' %}">Mağaza</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'store:cart' %}">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'store:checkout' %}">Ödeme</a>
                    </li>
                </ul>

                {% if user.is_authenticated == False %}
                <div class="form-inline my-2 my-lg-0" id="form-things">
                    <a class="btn btn-warning" href="#" id="form-login-button">Login</a>
                    <a href="{% url 'store:cart' %}">
                        <img id="cart-icon" src="{% static 'images/cart.png' %}" alt="cart.png">
                    </a>
                    <p id="cart-total">{{ order.summary_item_count }}</p>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    

    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- JQuerry -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- External JavaScript -->
    <script src="{% static 'js/cart.js' %}"></script>
</body>

</html>

vatancomputer/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}



<!-- Container -->
<div class="container-md">
    <div class="cards">
        {% for product in products %}
        <div class="cards-item card">
            <img src="{{ product.getImage }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ product.brand }} {{ product.name }}</h5>
                <small style="display: inline-block;min-height: 68px;" class="card-text">
                    {{ product.summary }}
                </small>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <button data-product="{{ product.id }}" data-action="add" class="btn btn-success update-cart">Satın Al</button>
                        <a href="{% url 'store:view' productId=product.id %}" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4 style="font-size: 1em;">{{ product.price|floatformat:2 }} <span style="font-size: 0.8em;">TL</span></h4>
                </span>
            </div>
        </div>
        {% endfor %}

        <!--Gereksizler 
        <div class="cards-item card">
            <img src="{% static 'images/book_image.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>

        <div class="cards-item card">
            <img src="{% static 'images/headphones.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>

        <div class="cards-item card">
            <img src="{% static 'images/shoes_image.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>

        <div class="cards-item card">
            <img src="{% static 'images/source_code_image.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>

        <div class="cards-item card">
            <img src="{% static 'images/thirt_image.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>

        <div class="cards-item card">
            <img src="{% static 'images/watch_image.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <hr>
                <span id="card-bottom">
                    <div class="btn-group">
                        <a href="#" class="btn btn-success">Satın Al</a>
                        <a href="#" class="btn btn-outline-secondary">İncele</a>
                    </div>
                    <h4>200 TL</h4>
                </span>
            </div>
        </div>
         -->
    </div>
</div>
{% endblock %}